/*
 * This file is generated by jOOQ.
 */
package com.example.ignitis_job_test.JooqGenerated;


import com.example.ignitis_job_test.JooqGenerated.tables.Admins;
import com.example.ignitis_job_test.JooqGenerated.tables.Messages;
import com.example.ignitis_job_test.JooqGenerated.tables.Users;
import com.example.ignitis_job_test.JooqGenerated.tables.records.AdminsRecord;
import com.example.ignitis_job_test.JooqGenerated.tables.records.MessagesRecord;
import com.example.ignitis_job_test.JooqGenerated.tables.records.UsersRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * IGNITIS.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AdminsRecord> PK_ADMINS = Internal.createUniqueKey(Admins.ADMINS, DSL.name("PK_ADMINS"), new TableField[] { Admins.ADMINS.ID }, true);
    public static final UniqueKey<AdminsRecord> UK_USERS_ADMIN_NAME = Internal.createUniqueKey(Admins.ADMINS, DSL.name("UK_USERS_ADMIN_NAME"), new TableField[] { Admins.ADMINS.ADMIN_NAME }, true);
    public static final UniqueKey<MessagesRecord> PK_MESSAGES = Internal.createUniqueKey(Messages.MESSAGES, DSL.name("PK_MESSAGES"), new TableField[] { Messages.MESSAGES.ID }, true);
    public static final UniqueKey<UsersRecord> PK_USERS = Internal.createUniqueKey(Users.USERS, DSL.name("PK_USERS"), new TableField[] { Users.USERS.ID }, true);
    public static final UniqueKey<UsersRecord> UK_USERS_USER_NAME = Internal.createUniqueKey(Users.USERS, DSL.name("UK_USERS_USER_NAME"), new TableField[] { Users.USERS.USER_NAME }, true);
}
