/*
 * This file is generated by jOOQ.
 */
package com.example.ignitis_job_test.JooqGenerated;


import com.example.ignitis_job_test.JooqGenerated.tables.Admins;
import com.example.ignitis_job_test.JooqGenerated.tables.Messages;
import com.example.ignitis_job_test.JooqGenerated.tables.Users;


/**
 * Convenience access to all tables in IGNITIS.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>IGNITIS.ADMINS</code>.
     */
    public static final Admins ADMINS = Admins.ADMINS;

    /**
     * The table <code>IGNITIS.MESSAGES</code>.
     */
    public static final Messages MESSAGES = Messages.MESSAGES;

    /**
     * The table <code>IGNITIS.USERS</code>.
     */
    public static final Users USERS = Users.USERS;
}
