/*
 * This file is generated by jOOQ.
 */
package com.example.ignitis_job_test.JooqGenerated.tables.records;


import com.example.ignitis_job_test.JooqGenerated.tables.Messages;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MessagesRecord extends UpdatableRecordImpl<MessagesRecord> implements Record5<Long, String, String, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>IGNITIS.MESSAGES.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>IGNITIS.MESSAGES.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>IGNITIS.MESSAGES.CREATOR</code>.
     */
    public void setCreator(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>IGNITIS.MESSAGES.CREATOR</code>.
     */
    public String getCreator() {
        return (String) get(1);
    }

    /**
     * Setter for <code>IGNITIS.MESSAGES.MESSAGE</code>.
     */
    public void setMessage(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>IGNITIS.MESSAGES.MESSAGE</code>.
     */
    public String getMessage() {
        return (String) get(2);
    }

    /**
     * Setter for <code>IGNITIS.MESSAGES.SENT_TO</code>.
     */
    public void setSentTo(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>IGNITIS.MESSAGES.SENT_TO</code>.
     */
    public String getSentTo() {
        return (String) get(3);
    }

    /**
     * Setter for <code>IGNITIS.MESSAGES.SENT_TIME</code>.
     */
    public void setSentTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>IGNITIS.MESSAGES.SENT_TIME</code>.
     */
    public LocalDateTime getSentTime() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, String, String, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, String, String, String, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Messages.MESSAGES.ID;
    }

    @Override
    public Field<String> field2() {
        return Messages.MESSAGES.CREATOR;
    }

    @Override
    public Field<String> field3() {
        return Messages.MESSAGES.MESSAGE;
    }

    @Override
    public Field<String> field4() {
        return Messages.MESSAGES.SENT_TO;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Messages.MESSAGES.SENT_TIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCreator();
    }

    @Override
    public String component3() {
        return getMessage();
    }

    @Override
    public String component4() {
        return getSentTo();
    }

    @Override
    public LocalDateTime component5() {
        return getSentTime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCreator();
    }

    @Override
    public String value3() {
        return getMessage();
    }

    @Override
    public String value4() {
        return getSentTo();
    }

    @Override
    public LocalDateTime value5() {
        return getSentTime();
    }

    @Override
    public MessagesRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public MessagesRecord value2(String value) {
        setCreator(value);
        return this;
    }

    @Override
    public MessagesRecord value3(String value) {
        setMessage(value);
        return this;
    }

    @Override
    public MessagesRecord value4(String value) {
        setSentTo(value);
        return this;
    }

    @Override
    public MessagesRecord value5(LocalDateTime value) {
        setSentTime(value);
        return this;
    }

    @Override
    public MessagesRecord values(Long value1, String value2, String value3, String value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessagesRecord
     */
    public MessagesRecord() {
        super(Messages.MESSAGES);
    }

    /**
     * Create a detached, initialised MessagesRecord
     */
    public MessagesRecord(Long id, String creator, String message, String sentTo, LocalDateTime sentTime) {
        super(Messages.MESSAGES);

        setId(id);
        setCreator(creator);
        setMessage(message);
        setSentTo(sentTo);
        setSentTime(sentTime);
        resetChangedOnNotNull();
    }
}
